# Generated by Django 3.2 on 2021-06-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210615_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='default_adress',
            new_name='default_address',
        ),
    ]
