# Generated by Django 3.2 on 2021-06-15 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='省市', to='areas.area')),
            ],
            options={
                'verbose_name': '省市区数据',
                'verbose_name_plural': '省市区数据',
                'db_table': 'tb_area',
            },
        ),
    ]
