# Generated by Django 3.2 on 2021-06-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_column='Name', max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(db_column='ParentId', on_delete=django.db.models.deletion.CASCADE, related_name='省市', to='areas.area'),
        ),
    ]
